SELECT L.NOMBRE, SUM(C.PRECIO_UNITARIO) AS PRECIO_TOTAL
FROM LISTAS_DE_REPRODUCCION L
JOIN CANCIONES_EN_LISTA CEL ON L.ID = CEL.LISTA_ID
JOIN CANCIONES C ON CEL.CANCION_ID = C.ID
GROUP BY L.ID, L.NOMBRE;