SELECT L.NOMBRE, SUM(C.PRECIO_UNITARIO) AS PRECIO_TOTAL
FROM LISTAS_DE_REPRODUCCION L
JOIN CANCIONES_EN_LISTA CEL ON L.ID = CEL.LISTA_ID
JOIN CANCIONES C ON CEL.CANCION_ID = C.ID
GROUP BY L.ID, L.NOMBRE;

SELECT L.NOMBRE, SUM(C.PRECIO_UNITARIO) AS PRECIO_TOTAL
FROM LISTAS_DE_REPRODUCCION L
INNER JOIN CANCIONES_EN_LISTA CEL ON L.ID = CEL.LISTA_ID
INNER JOIN CANCIONES C ON CEL.CANCION_ID = C.ID
GROUP BY L.ID, L.NOMBRE;
ORDER BY PRECIO_TOTAL DESC
FETCH FIRST 3 ROWS ONLY;


SELECT C
FROM CANCIONES C
LEFT JOIN CANCIONES_EN_LISTA CEL ON C.ID = CEL.CANCION_ID
LEFT JOIN LISTAS_DE_REPRODUCCION L ON CEL.LISTA_ID = L.ID

WHERE L.ID IS NULL;
wHERE 

SELECT *
FROM GENEROS