-- =========================================================
-- Base de datos: Oracle (tipos VARCHAR2, NUMBER)
-- =========================================================

-- Nota: Si necesitas rehacer el esquema, primero elimina las tablas.
-- (Opcional) Descomenta estas líneas en orden inverso para limpiar:
-- DROP TABLE CANCIONES_EN_LISTA CASCADE CONSTRAINTS;
-- DROP TABLE CANCIONES CASCADE CONSTRAINTS;
-- DROP TABLE LISTAS_DE_REPRODUCCION CASCADE CONSTRAINTS;
-- DROP TABLE TIPOS_MEDIO CASCADE CONSTRAINTS;
-- DROP TABLE GENEROS CASCADE CONSTRAINTS;
-- DROP TABLE ALBUMES CASCADE CONSTRAINTS;
-- DROP TABLE ARTISTAS CASCADE CONSTRAINTS;

-- 1) ARTISTAS
CREATE TABLE ARTISTAS (
  ID      NUMBER        NOT NULL,
  NOMBRE  VARCHAR2(120 BYTE)
);

ALTER TABLE ARTISTAS
  ADD CONSTRAINT ARTISTAS_PK PRIMARY KEY (ID);

-- 2) ALBUMES (FK -> ARTISTAS)
CREATE TABLE ALBUMES (
  ID          NUMBER           NOT NULL,
  TITULO      VARCHAR2(160 BYTE),
  ARTISTA_ID  NUMBER           NOT NULL
);


ALTER TABLE ALBUMES
  ADD CONSTRAINT ALBUMES_PK PRIMARY KEY (ID);

ALTER TABLE ALBUMES
  ADD CONSTRAINT ALBUMES_ARTISTAS_FK
  FOREIGN KEY (ARTISTA_ID)
  REFERENCES ARTISTAS (ID);

-- 3) GENEROS
CREATE TABLE GENEROS (
  ID      NUMBER        NOT NULL,
  NOMBRE  VARCHAR2(120 BYTE)
);

ALTER TABLE GENEROS
  ADD CONSTRAINT GENEROS_PK PRIMARY KEY (ID);

-- 4) TIPOS_MEDIO
CREATE TABLE TIPOS_MEDIO (
  ID      NUMBER        NOT NULL,
  NOMBRE  VARCHAR2(120 BYTE)
);

ALTER TABLE TIPOS_MEDIO
  ADD CONSTRAINT TIPOS_MEDIO_PK PRIMARY KEY (ID);

-- 5) CANCIONES (FK -> ALBUMES, GENEROS, TIPOS_MEDIO)
CREATE TABLE CANCIONES (
  ID               NUMBER            NOT NULL,
  NOMBRE           VARCHAR2(200 BYTE),
  ALBUM_ID         NUMBER,
  MEDIO_ID         NUMBER,
  GENERO_ID        NUMBER,
  COMPOSITOR       VARCHAR2(220 BYTE),
  MILISEGUNDOS     NUMBER,
  BYTES            NUMBER,
  PRECIO_UNITARIO  NUMBER(10,2)
);

ALTER TABLE CANCIONES
  ADD CONSTRAINT CANCIONES_PK PRIMARY KEY (ID);

ALTER TABLE CANCIONES
  ADD CONSTRAINT CANCIONES_ALBUMES_FK
  FOREIGN KEY (ALBUM_ID)
  REFERENCES ALBUMES (ID);

ALTER TABLE CANCIONES
  ADD CONSTRAINT CANCIONES_GENEROS_FK
  FOREIGN KEY (GENERO_ID)
  REFERENCES GENEROS (ID);

ALTER TABLE CANCIONES
  ADD CONSTRAINT CANCIONES_TIPOS_MEDIO_FK
  FOREIGN KEY (MEDIO_ID)
  REFERENCES TIPOS_MEDIO (ID);

-- 6) LISTAS_DE_REPRODUCCION
CREATE TABLE LISTAS_DE_REPRODUCCION (
  ID      NUMBER           NOT NULL,
  NOMBRE  VARCHAR2(120 BYTE)
);

ALTER TABLE LISTAS_DE_REPRODUCCION
  ADD CONSTRAINT LISTAS_DE_REPRODUCCION_PK PRIMARY KEY (ID);

-- 7) CANCIONES_EN_LISTA (relación N:M entre LISTAS_DE_REPRODUCCION y CANCIONES)
CREATE TABLE CANCIONES_EN_LISTA (
  LISTA_ID    NUMBER    NOT NULL,
  CANCION_ID  NUMBER    NOT NULL
);

ALTER TABLE CANCIONES_EN_LISTA
  ADD CONSTRAINT CANCIONES_EN_LISTA_PK
  PRIMARY KEY (LISTA_ID, CANCION_ID);

ALTER TABLE CANCIONES_EN_LISTA
  ADD CONSTRAINT CANCIONES_EN_LISTA_LISTAS_DE_REPRODUCCION_FK
  FOREIGN KEY (LISTA_ID)
  REFERENCES LISTAS_DE_REPRODUCCION (ID);

ALTER TABLE CANCIONES_EN_LISTA
  ADD CONSTRAINT CANCIONES_EN_LISTA_CANCIONES_FK
  FOREIGN KEY (CANCION_ID)
  REFERENCES CANCIONES (ID);




SELECT L.NOMBRE, COUNT(CEL.CANCION_ID) AS NUM_CANCIONES
FROM LISTAS_DE_REPRODUCCION L
JOIN CANCIONES_EN_LISTA CEL ON L.ID = CEL.LISTA_ID
GROUP BY L.ID, L.NOMBRE
ORDER BY NUM_CANCIONES DESC
FETCH FIRST 3 ROWS ONLY;